language: node_js

sudo: required

node_js:
  - "6.3"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libgnome-keyring-dev

env:
  - CXX=g++-4.8

before_install:
  - npm install -g npm@latest
  - npm install -g ethereumjs-testrpc truffle

install:
  - export CXX="g++-4.8"
  - npm install 

script:
  - testrpc &
  - truffle test

