language: node_js
sudo: required

node_js:
  - "6.3.1"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - xvfb
      - libgnome-keyring-dev

env:
  - CXX=g++-4.8

cache:
  directories:
    - node_modules

before_install:
  - npm install -g npm@latest
  - npm install -g ethereumjs-testrpc truffle

install:
  - export CXX="g++-4.8"
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install 

script:
  - testrpc
