language: node_js

sudo: required

node_js:
  - "6"
  - "6.1"
  - "6.2"
  - "6.3"
  - "6.4"
  - "6.5"
  - "6.6"
  - "6.7"
  - "6.8"
  - "6.9"
  - "7.0"
  - "7.1"
  - "7.2"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - xvfb
      - libgnome-keyring-dev

env:
  - CXX=g++-4.8

before_install:
  - npm install -g npm@latest
  - npm install -g ethereumjs-testrpc truffle

install:
  - export CXX="g++-4.8"
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install 

script:
  - testrpc &
  - truffle test

