language: node_js
sudo: required 
node_js:
  - "6"
  - "6.1"
  - "6.3"
before_install:
  - rm -rf node_modules
install:
  - sudo dpkg -i build-essential
  - sudo apt-get install
  - npm install
  - npm install -g node-gyp
  - npm install -g ethereumjs-testrpc truffle

script:
  - truffle test
