language: node_js
node_js:
  - "6"
  - "6.1"
  - "6.3"
before_install:
  - rm -rf node_modules
install:
  - apt-get install build-essential
  - apt-get install libkrb5-dev
  - npm install
  - npm install -g node-gyp
  - npm install -g ethereumjs-testrpc truffle

script:
  - truffle test
