language: node_js

sudo: required

node_js:
  - "6.3"

addons:
  apt:
    packages:
      - build-essential
      - g++

before_install:
  - export CXX="g++-4.8"
  - npm install -g npm@latest
  - npm install -g ethereumjs-testrpc truffle

install:
  - npm install 

script:
  - testrpc &
  - truffle test

